require: rubocop-rails

Rails/FindBy:
  Exclude:
    - lib/example.rb

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false
